--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Blugin/virions
build-by-default: true
branches:
- master
projects:
  MultilingualConfigTrait:
    path: MultilingualConfigTrait
    model: virion
    type: library
    lint:
      phpstan: false
  LocaleConverter:
    path: LocaleConverter
    model: virion
    type: library
    lint:
      phpstan: false
  libtranslator:
    path: libtranslator
    model: virion
    type: library
    lint:
      phpstan: false
...
