--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/PresentKim/locale-converter
branches:
  - main
projects:
  locale-converter:
    model: virion
    type: library
    lint:
      phpstan: false
...
